### ISSUE TITLE
EngineIO Client could not keep connection alive when using SSL

### ISSUE THREAD

**Issue by matrixcloud** [socketio/engine.io-server-java#16]
Hi,

I tried to connect an SSL engine-io server but got failed.

## Server Code

The following is my server code, I deploy the servlet in a `Jetty Container` which is using SSL.

```java
public class SockServlet extends HttpServlet {
    private final EngineIoServer mEngineIoServer = new EngineIoServer();
    private static final Logger logger = Logger.getLogger(ConnectionListener.class.getName());

    @Override
    public void init(ServletConfig config) throws ServletException {
        super.init(config);
        logger.info("Sock Servlet Initialized");

        initIO();
    }

    private void initIO() {
        mEngineIoServer.on("connection", new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                EngineIoSocket socket = (EngineIoSocket) args[0];
                logger.info("A client connected: " + socket.getId());
                socket.send(new Packet<>(Packet.MESSAGE, "Hi client, I am here"));

                socket.on("message", new Emitter.Listener() {
                    @Override
                    public void call(Object... objects) {
                        String message = (String) objects[0];
                        logger.info("received: " + message);
                        logger.info("received");
                    }
                });
            }
        });
    }

    @Override
    protected void service(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        mEngineIoServer.handleRequest(req, resp);
    }

    public EngineIoServer getmEngineIoServer() {
         return mEngineIoServer;
    }
}
```

**maven dependency**
```xml
<dependency>
        <groupId>io.socket</groupId>
        <artifactId>engine.io-server</artifactId>
        <version>1.3.1</version>
</dependency>
```

## Client Code

I created an engine-io client using engine.io-client.

```javascript
const io = require('engine.io-client');

const opts = {
  path: '/rest-api/sock',
  rejectUnauthorized: false,
};

const socket = io('https://localhost:8443', opts);
socket.on('open', () => {
  console.log('connected');
})
socket.on('message', (data) => {
  console.log('received: ', data);
});

socket.on('error', (err) => {
  console.log('error', err);
})

console.log('client started');
```

**dependency**
```json
 "engine.io-client": "^3.2.1",
```

## Errors

When I executed the client code using `node client.js`, it showed the first connection has been established, but the connection couldn't keep alive.

```
client started
connected
received:  Hi client, I am here
error { Error: xhr poll error
    at XHR.Transport.onError (C:\Projects\history-notification-client\node_modules\engine.io-client\lib\transport.js:67:13)
    at Request.<anonymous> (C:\Projects\history-notification-client\node_modules\engine.io-client\lib\transports\polling-xhr.js:130:10)
    at Request.Emitter.emit (C:\Projects\history-notification-client\node_modules\component-emitter\index.js:133:20)
    at Request.onError (C:\Projects\history-notification-client\node_modules\engine.io-client\lib\transports\polling-xhr.js:311:8)
    at Timeout._onTimeout (C:\Projects\history-notification-client\node_modules\engine.io-client\lib\transports\polling-xhr.js:258:18)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) type: 'TransportError', description: 503 }
```

**Comment by matrixcloud** [comment]
My further investigation below.

```
engine.io-client:polling-xhr xhr open POST: https://localhost:8443/rest-api/sock/?EIO=3&transport=polling&t=MegRN4b&b64=1&sid=MegEN9J +9ms
  engine.io-client:polling-xhr xhr data 1:1 +0ms
  engine.io-client:polling-xhr xhr1 XMLHttpRequest {
  UNSENT: 0,
  OPENED: 1,
  HEADERS_RECEIVED: 2,
  LOADING: 3,
  DONE: 4,
  readyState: 4,
  onreadystatechange: [Function],
  responseText: 'Error: read ECONNRESET\n    at TLSWrap.onread (net.js:622:25)',
  responseXML: '',
  status: 503,
  statusText: { Error: read ECONNRESET
    at TLSWrap.onread (net.js:622:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },
  open: [Function],
  setDisableHeaderCheck: [Function],
  setRequestHeader: [Function],
  getResponseHeader: [Function],
  getAllResponseHeaders: [Function],
  getRequestHeader: [Function],
  send: [Function],
  handleError: [Function],
  abort: [Function],
  addEventListener: [Function],
  removeEventListener: [Function],
  dispatchEvent: [Function] } +16ms
```

`node -v` shows `v8.14.0`

**Comment by trinopoty** [comment]
Also, I'm don't know what browser you're using but https to localhost seems troublesome and could be the thing causing the issue.

**Comment by matrixcloud** [comment]
@trinopoty  I can ensure the server is available, and from the logs, you can see that the first connection has been established because the client received a message from server `received:  Hi client, I am here`.

I used the engine-client in node. I will try to config the ssl options.

Thanks for your quick reply!

**Comment by matrixcloud** [comment]
It seems the error caused by the server since I tried a simple demo and it connected successfully.

**Comment by trinopoty** [comment]
I see. Thanks for the update.

**Comment by matrixcloud** [comment]
I have found the root cause, it's caused by `org.eclipse.jetty.servlets.DoSFilter`.
